In [2]:
import numpy as np

In [3]:
#Creating Numby 
arr=np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [4]:
#type present in numby

print(type(arr))

<class 'numpy.ndarray'>


In [5]:
#Slicing Numby
arr=np.array([10,20,30,40])
print(arr[0:2])#Startig Value
print(arr[:2])#Another format
print(arr[2:])#Endind value

[10 20]
[10 20]
[30 40]


In [6]:
print(arr[::3])

[10 40]


In [7]:
#Resversing Array
print(arr[::-1])

[40 30 20 10]


In [8]:
#To find list inside list
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr[1:3,1:3])

[[60 70]]


In [9]:
arr[0,0:2]

array([10, 20])

In [10]:
arr[1,0:2]

array([50, 60])

In [11]:
#Shape of array
np.shape(arr)

(2, 4)

In [12]:
np.size(arr)

8

In [13]:
#Dimension of Array
np.ndim(arr)

2

In [14]:
#Datatype of array
arr.dtype

dtype('int32')

In [15]:
#Numby Function
#arange() method -Syntax:-arange([start],[stop],[step],[dtype])
arr=np.arange(1,6,2,dtype=int)
arr

array([1, 3, 5])

In [16]:
#zeros() method -returns a new array of given shape and type,with zeros
print(np.zeros((3,3),dtype=int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [17]:
#ones() method -reeturns a new array of given shape and type,with ones
print(np.ones((3,3),dtype=int))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [18]:
#full() method - Syntax numpy.full(shape,fill_value,dtype)
print(np.full((2,3),8,dtype=int))

[[8 8 8]
 [8 8 8]]


In [19]:
print(np.arange(9).reshape(3,-1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
#Repeat ()-Repeat the elements of the arrary
#arr=np.repeat(3,5,axis=0)
arr=np.repeat([[3,2]],5,axis=0)#Vertical axis=0
arr

array([[3, 2],
       [3, 2],
       [3, 2],
       [3, 2],
       [3, 2]])

In [21]:
arr=np.repeat([[3,2]],5,axis=1)#horizontal axis=1
arr

array([[3, 3, 3, 3, 3, 2, 2, 2, 2, 2]])

In [22]:
#Concatenate() method-single dimension
arr=np.array([1,2,3,4])
arr1=np.array([5,6,7,8])
c=np.concatenate([arr,arr1])
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
#Concatenate() method-Multi dimension
arr=np.array([[1,2,3,4],[1,2,3,4]])
arr1=np.array([[5,6,7,8],[5,6,7,8]])
c=np.concatenate([arr,arr1],axis=0)#-vertical axis
#c=np.concatenate([arr,arr1],axis=1)#-horizontal axis
c

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [26]:
#VStack method is used to stack the sequence of vertical axis 
v=np.vstack([arr,arr1])
v

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [29]:
#r_Statement is  translates slice objects to concatenation along the first axis
r=np.r_[arr,arr1]
r

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [30]:
#hstack is used to stack the sequence of input arrays horizontally to make a single array
h=np.hstack([arr,arr1])
h

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [35]:
#power() method it is used to  get one array containing elements of the first array 
#raised to the power element of the second array
arr=np.array([[1,2,3,4],[1,2,3,4]])
p=np.power(arr,[2,2,3,2])
p

array([[ 1,  4, 27, 16],
       [ 1,  4, 27, 16]])

In [42]:
#diff() methosd is used when we calculate the nth order discrete 
#difference along the given axis
arr=np.array([1,2,3,4])
arr1=np.array([5,6,7,8])
#d=np.diff(arr)
d=np.diff((arr,arr1),axis=0)
d

array([[4, 4, 4, 4]])

In [41]:
#Cross it returns the cross product of two vectors
arr=np.array([1,2,3])
arr1=np.array([5,6,7])
c=np.cross(arr,arr1)
c

array([-4,  8, -4])

In [50]:
#sort this method returns the sorted copy of an array
arr=np.array([1,3,8,9])
arr1=np.array([5,2,4,6])
#s=np.sort((arr,arr1),axis=0)
s=np.sort((arr,arr1),axis=1)
s

array([[1, 3, 8, 9],
       [2, 4, 5, 6]])

In [ ]:
#Flatten is used to flatten a matrix to one dimension in python
