Course 2: Python for Data Science

1) Numpy Arrays
2) Series
3) Data Frame

Sprint 1: Creating, Manipulating NumPy Arrays

What is NumPy Array?

Numpy array is NDimensional array holds same kind of data...it is homogeneous kind of data.

In [14]:
import numpy as np

In [13]:
print(np.__version__)

1.26.4


In [ ]:
numpy.array()

In [16]:
t=np.array((1,2,3))

In [18]:
t

array([1, 2, 3])

In [20]:
t=np.array([1,2,3])

In [22]:
t

array([1, 2, 3])

In [14]:
l1 = [1,2,3]

In [15]:
arr = np.array(l1)

In [16]:
arr

array([1, 2, 3])

In [17]:
arr+3

array([4, 5, 6])

There are four Basic Methods to understand about numpy array

1) Size

2) ndim

3) shape

4) dtype

In [19]:
arr.size

3

In [20]:
arr.ndim

1

In [21]:
arr.shape

(3,)

In [22]:
arr.dtype

dtype('int32')

In [2]:
np.zeros((3,2))   # To have only zeros in the array

NameError: name 'np' is not defined

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
a = np.identity(5)

In [32]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a.ndim

2

In [28]:
a.shape

(3, 3)

np.arange(start, stop, step, dtype)

In [30]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [32]:
np.random.random(size = 10)

array([0.68635272, 0.50573177, 0.5040064 , 0.18490686, 0.06325953,
       0.45412853, 0.61323947, 0.59950828, 0.92839818, 0.50307692])

In [33]:
np.random.random()

0.9193798989143646

In [34]:
from numpy import random

In [35]:
random.random()

0.12276714590425586

np.random.randint(max value, size)

In [37]:
np.random.randint(10)

6

In [38]:
np.random.randint(10, size = 6)

array([2, 5, 5, 9, 3, 9])

In [39]:
np.random.seed(42)

In [40]:
a = np.random.randint(10, size = 6)

In [41]:
a

array([6, 3, 7, 4, 6, 9])

In [40]:
s = np.random.randint(10000,21000,2000)

In [42]:
s

array([10443, 15595, 10281, ..., 19768, 11973, 19761])

In [44]:
avg = np.mean(s)

In [45]:
avg

15503.3015

In [46]:
max = np.max(s)

In [47]:
max

20998

In [48]:
n=np.array([[1,2,3,4,5]
            [6,10,9,8,7]])
np.max(n,axis=0)

array([ 6, 10,  9,  8,  7])

In [49]:
n=np.array([[1,2,3,4,5],
            [6,10,9,8,7]])
np.max(n,axis=1)

array([ 5, 10])

In [50]:
min = np.min(s)
min

10001

In [51]:
n=np.array([[1,2,3,4,5],[6,10,9,8,7]])
np.min(n,axis=0)

array([1, 2, 3, 4, 5])

In [52]:
n=np.array([[1,2,3,4,5],[6,10,9,8,7]])
np.min(n,axis=1)

array([1, 6])

In [53]:
std = np.std(s)
std

3150.4637281831624

In [44]:
s

array([10443, 15595, 10281, ..., 19768, 11973, 19761])

In [54]:
s[0]

10466

In [55]:
s[1]

14426

In [56]:
s[-1]

19539

In [57]:
s[1:100]

array([14426, 15578, 18322, 11685, 10769, 20583, 16949, 12433, 15311,
       15051, 16420, 11184, 14555, 13385, 16396, 18666, 19274, 12558,
       17849, 12047, 12747, 19167, 19998, 10189, 12734, 13005, 14658,
       11899, 17734, 11267, 11528, 13556, 13890, 18838, 15393, 20627,
       18792, 20555, 20253, 18433, 20233, 17513, 12612, 17041, 19555,
       16235, 15486, 17099, 19670, 20748, 10775, 18226, 13152, 20147,
       11585, 13943, 17555, 13073, 11021, 20805, 13843, 17989, 19692,
       16873, 15675, 10161, 14297, 20173, 10995, 17629, 19467, 11016,
       17869, 16439, 17892, 16863, 17916, 18529, 10878, 19268, 14887,
       14859, 16331, 18571, 18684, 17208, 15276, 12062, 10064, 18006,
       12568, 15463, 12027, 12695, 19687, 15258, 15618, 16736, 10391])

In [58]:
s[0] = 20000

In [59]:
s[0]

20000

In [60]:
print(s>20000)

[False False False ... False False False]


In [61]:
s[s>20000]

array([20583, 20627, 20555, 20253, 20233, 20748, 20147, 20805, 20173,
       20470, 20965, 20882, 20817, 20921, 20173, 20230, 20429, 20867,
       20352, 20969, 20248, 20927, 20677, 20716, 20757, 20492, 20257,
       20729, 20647, 20893, 20966, 20174, 20852, 20486, 20457, 20262,
       20123, 20636, 20738, 20966, 20518, 20011, 20808, 20578, 20048,
       20019, 20406, 20150, 20188, 20975, 20971, 20700, 20136, 20016,
       20344, 20948, 20916, 20015, 20273, 20357, 20176, 20040, 20314,
       20342, 20674, 20209, 20320, 20785, 20161, 20160, 20488, 20453,
       20478, 20247, 20958, 20267, 20348, 20350, 20852, 20167, 20554,
       20901, 20516, 20755, 20589, 20787, 20954, 20002, 20231, 20568,
       20230, 20161, 20813, 20641, 20535, 20055, 20343, 20818, 20227,
       20789, 20049, 20147, 20026, 20789, 20541, 20457, 20380, 20922,
       20314, 20395, 20454, 20524, 20353, 20093, 20015, 20998, 20682,
       20112, 20953, 20268, 20849, 20367, 20281, 20273, 20250, 20961,
       20653, 20616,

In [62]:
s[s%2 ==0]

array([20000, 14426, 15578, ..., 13230, 10488, 17114])

In [63]:
s[s%2 != 0]

array([11685, 10769, 20583, 16949, 12433, 15311, 15051, 14555, 13385,
       17849, 12047, 12747, 19167, 10189, 13005, 11899, 11267, 15393,
       20627, 20555, 20253, 18433, 20233, 17513, 17041, 19555, 16235,
       17099, 10775, 20147, 11585, 13943, 17555, 13073, 11021, 20805,
       13843, 17989, 16873, 15675, 10161, 14297, 20173, 10995, 17629,
       19467, 17869, 16439, 16863, 18529, 14887, 14859, 16331, 18571,
       15463, 12027, 12695, 19687, 10391, 13561, 13099, 17215, 12731,
       20965, 17385, 15977, 17721, 17035, 10863, 18755, 16019, 11757,
       11059, 13157, 15915, 20817, 20921, 19789, 12693, 13627, 19555,
       20173, 11663, 19721, 20429, 20867, 18901, 15575, 14413, 10663,
       11495, 13763, 11853, 16585, 11291, 13581, 14737, 15855, 15249,
       11707, 20969, 15791, 19925, 15535, 14931, 14389, 12327, 12931,
       17777, 10197, 17125, 16287, 19339, 12511, 10659, 12811, 19561,
       12911, 11843, 11959, 15759, 12385, 18155, 14061, 16287, 18815,
       12049, 15423,

In [64]:
arr = np.arange(0,21)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [66]:
arr<12

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False])

In [67]:
np.where(arr<12)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64),)

In [68]:
a = np.where(arr<12)
b = np.where(arr>15)
a and b

(array([16, 17, 18, 19, 20], dtype=int64),)

In [69]:
a

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64),)

In [70]:
b

(array([16, 17, 18, 19, 20], dtype=int64),)

In [71]:
a and b

(array([16, 17, 18, 19, 20], dtype=int64),)

In [72]:
a or b

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64),)

In [73]:
arr[np.where((arr<5) | (arr>12))]

array([ 0,  1,  2,  3,  4, 13, 14, 15, 16, 17, 18, 19, 20])

In [74]:
np.where(arr<10, arr*2, arr)   #update

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [75]:
np.where(arr<10, arr, arr*2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [76]:
c = np.copy(arr)

In [77]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

Delete

syntax = np.delete(array, object, axis=None)

In [80]:
np.delete(c, [0,3,2,10])

array([ 1,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Append

syntax = np.append(array, values, axis = None)

array = the input array
values = [int, array of int]

In [82]:
np.append(c, [0,3,2,10])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20,  0,  3,  2, 10])

Insert

In [171]:
n=np.insert(c,5,[20,60])

In [173]:
np.sort(n)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 20, 60])

In [175]:
np.sort(n)[::-1]

array([60, 20, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,
        5,  4,  3,  2,  1,  0])

In [179]:
n

array([ 0,  1,  2,  3,  4, 20, 60,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19, 20])

In [185]:
np.flip(n)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5, 60,
       20,  4,  3,  2,  1,  0])

In [2]:
a=[1,2,3,4]
b=a
c=a[:]

In [10]:
b is a

True