# Numby

## Numpy array is NDimensional array holds same kind of data...it is homogeneous kind of data.

In [4]:
import numpy as np

In [6]:
a=np.array((1,2,3))

In [8]:
a

array([1, 2, 3])

In [10]:
a=np.array([1,2,3])

In [12]:
a

array([1, 2, 3])

In [14]:
li=[1,2,3,4,5]

In [16]:
arr=np.array(li)

In [18]:
arr

array([1, 2, 3, 4, 5])

# Basics methos()

In [21]:
# Size
arr.size

5

In [23]:
arr.ndim

1

In [25]:
arr.shape

(5,)

In [27]:
arr.dtype

dtype('int32')

In [31]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
np.random.random(size=10)

array([0.62384452, 0.83497188, 0.68575945, 0.78960036, 0.78834566,
       0.94057098, 0.34412754, 0.91326439, 0.98807585, 0.04703386])

In [45]:
np.random.random()

0.3442555172695977

In [73]:
import random as ra

In [65]:
np.random.seed(42)

In [83]:
a=np.random.randint(10,size=6)

In [89]:
a

array([2, 6, 7, 4, 3, 7])

In [91]:
a.max()

7

In [93]:
a.min()

2

In [95]:
a.std()

1.950783318453271

In [97]:
a.mean()

4.833333333333333

In [99]:
np.append(a,[0,3,4,5])

array([2, 6, 7, 4, 3, 7, 0, 3, 4, 5])

In [105]:
np.delete(a,[4,3])

array([2, 6, 7, 7])

In [109]:
np.sort(a)[::-1]

array([7, 7, 6, 4, 3, 2])

In [111]:
np.flip(a)

array([7, 3, 4, 7, 6, 2])